"""Backward-compatibility re-export shim.

The canonical module is :mod:`asteroid_jumper.draw`.
This module re-exports everything from there so existing imports continue
to work without modification.
"""

from asteroid_jumper.draw import (  # noqa: F401
    C_BASE,
    C_BLUE,
    C_CRUST,
    C_FLAMINGO,
    C_GREEN,
    C_LAVENDER,
    C_MANTLE,
    C_MAUVE,
    C_PEACH,
    C_RED,
    C_SKY,
    C_SUBTEXT,
    C_SURFACE0,
    C_SURFACE1,
    C_TEAL,
    C_TEXT,
    C_YELLOW,
    JUMPER_HEIGHT_REF,
    STAR_POSITIONS,
    WorldToScreenFn,
    build_hud_lines,
    draw_arm,
    draw_arrowhead,
    draw_asteroid,
    draw_background,
    draw_craters,
    draw_hud_overlay,
    draw_jumper_body,
    draw_legs,
    draw_single_trail,
    draw_stars,
)

__all__ = [
    "C_BASE",
    "C_BLUE",
    "C_CRUST",
    "C_FLAMINGO",
    "C_GREEN",
    "C_LAVENDER",
    "C_MANTLE",
    "C_MAUVE",
    "C_PEACH",
    "C_RED",
    "C_SKY",
    "C_SUBTEXT",
    "C_SURFACE0",
    "C_SURFACE1",
    "C_TEAL",
    "C_TEXT",
    "C_YELLOW",
    "JUMPER_HEIGHT_REF",
    "STAR_POSITIONS",
    "WorldToScreenFn",
    "build_hud_lines",
    "draw_arm",
    "draw_arrowhead",
    "draw_asteroid",
    "draw_background",
    "draw_craters",
    "draw_hud_overlay",
    "draw_jumper_body",
    "draw_legs",
    "draw_single_trail",
    "draw_stars",
]
