"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import NotRequired, TypedDict

from completist_analyzers import _collect_report_data
from completist_issues import _create_high_impact_issues
from completist_report import (
    _build_report_lines,
    _save_report_files,
)

# Constants and Configuration
DATA_DIR = ".jules/completist_data"
REPORT_DIR = "docs/assessments/completist"
ISSUES_DIR = "docs/assessments/issues"

FILES_MAP = {
    "MARKERS": os.path.join(DATA_DIR, "todo_markers.txt"),
    "NOT_IMPL": os.path.join(DATA_DIR, "not_implemented.txt"),
    "STUBS": os.path.join(DATA_DIR, "stub_functions.txt"),
    "DOCS": os.path.join(DATA_DIR, "incomplete_docs.txt"),
    "ABSTRACT": os.path.join(DATA_DIR, "abstract_methods.txt"),
}

EXCLUDED_PATHS = [
    "scripts/analyze_completist_data.py",
    "docs/",
    ".github/",
    ".jules/",
    "CRITICAL_PROJECT_REVIEW.md",
    "WORKFLOW_AND_AGENTS_REPORT.md",
    "pyproject.toml",
]


logger = logging.getLogger(__name__)


class Finding(TypedDict):
    file: str
    line: str
    type: str
    text: NotRequired[str]
    name: NotRequired[str]


def generate_report() -> None:
    """Generate the structured completist status report."""
    date_s = datetime.now().strftime("%Y-%m-%d")
    criticals, todos, fixmes, missing_docs = _collect_report_data()
    report_lines = _build_report_lines(date_s, criticals, todos, fixmes, missing_docs)
    report_lines.extend(_create_high_impact_issues(criticals))
    _save_report_files(date_s, "\n".join(report_lines))


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    generate_report()
