"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import logging
import os
from collections.abc import Callable, Mapping
from typing import Any, NotRequired, TypedDict, cast

# Constants and Configuration
DATA_DIR = ".jules/completist_data"
REPORT_DIR = "docs/assessments/completist"
ISSUES_DIR = "docs/assessments/issues"

FILES_MAP = {
    "MARKERS": os.path.join(DATA_DIR, "todo_markers.txt"),
    "NOT_IMPL": os.path.join(DATA_DIR, "not_implemented.txt"),
    "STUBS": os.path.join(DATA_DIR, "stub_functions.txt"),
    "DOCS": os.path.join(DATA_DIR, "incomplete_docs.txt"),
    "ABSTRACT": os.path.join(DATA_DIR, "abstract_methods.txt"),
}

EXCLUDED_PATHS = [
    "scripts/analyze_completist_data.py",
    "docs/",
    ".github/",
    ".jules/",
    "CRITICAL_PROJECT_REVIEW.md",
    "WORKFLOW_AND_AGENTS_REPORT.md",
    "pyproject.toml",
]


logger = logging.getLogger(__name__)


class Finding(TypedDict):
    file: str
    line: str
    type: str
    text: NotRequired[str]
    name: NotRequired[str]


def is_excluded(filepath: str) -> bool:
    """Check if filepath should be excluded from analysis."""
    if not filepath:
        return True

    fp = filepath.replace("\\", "/")
    if fp.startswith("./"):
        fp = fp[2:]

    for excl in EXCLUDED_PATHS:
        if fp.startswith(excl) or excl in fp:
            return True
    return False


def _parse_grep_line(line: str) -> tuple[str | None, str | None, str | None]:
    """Parse a standard 'file:line:content' grep output line."""
    parts = line.split(":", 2)
    if len(parts) < 3:
        return None, None, None
    return parts[0], parts[1], parts[2].strip()


def _scan_completist_file(
    source_key: str, parser: Callable[[str], Finding | None]
) -> list[Finding]:
    """Generic helper to scan a completist data file and parse findings."""
    source_path = FILES_MAP.get(source_key)
    if not source_path or not os.path.exists(source_path):
        return []

    results: list[Finding] = []
    with open(source_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            finding = parser(line)
            if finding and not is_excluded(finding["file"]):
                results.append(finding)
    return results


def calculate_metrics(item: Mapping[str, Any]) -> tuple[int, int, int]:
    """Calculate heuristics for Impact, Coverage, and Complexity (1-5 range)."""
    filepath = cast(str, item["file"])
    itype = cast(str, item.get("type", ""))

    impact = (
        5
        if any(x in filepath for x in ["shared/python", "engines/", "api/"])
        else (3 if "tools/" in filepath else 1)
    )
    coverage = 5 if "tests/" in filepath else (3 if "shared/python" in filepath else 2)

    # Complexity mapping
    comp_map = {
        "Stub": 4,
        "NotImplementedError": 4,
        "TRACKED_DEFECT": 2,
        "TRACKED_TASK": 3,
        "DocGap": 1,
        "Abstract": 5,
    }
    complexity = comp_map.get(itype, 3)

    return impact, coverage, complexity
