"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import logging
import os
from collections.abc import Mapping
from typing import Any

from completist_utils import Finding, calculate_metrics

# Constants and Configuration
REPORT_DIR = "docs/assessments/completist"


logger = logging.getLogger(__name__)


def _status_overview_chart(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    docs: list[Finding],
) -> list[str]:
    """Build Mermaid pie-chart lines for completion status overview."""
    return [
        "### Status Overview",
        "```mermaid",
        "pie title Completion Status",
        f'    "Impl Gaps (Critical)" : {len(criticals)}',
        f'    "Feature Requests (TRACKED_TASK)" : {len(todos)}',
        f'    "Technical Debt (TRACKED_DEFECT)" : {len(fixmes)}',
        f'    "Doc Gaps" : {len(docs)}',
        "```",
    ]


def _module_breakdown_chart(
    criticals: list[Finding], todos: list[Finding], fixmes: list[Finding]
) -> list[str]:
    """Build Mermaid pie-chart lines for top impacted modules."""
    counts: dict[str, int] = {}
    for item in criticals + todos + fixmes:
        path_parts = item["file"].split("/")
        root = path_parts[0] if path_parts else "unknown"
        if root in [".", "src"]:
            root = path_parts[1] if len(path_parts) > 1 else root
        counts[root] = counts.get(root, 0) + 1
    sorted_mods = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
    if not sorted_mods:
        return []
    lines = ["\n### Top Impacted Modules", "```mermaid", "pie title Issues by Module"]
    lines.extend(f'    "{mod}" : {count}' for mod, count in sorted_mods)
    lines.append("```")
    return lines


def generate_mermaid_charts(
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    docs: list[Finding],
) -> str:
    """Generate Mermaid charts for the report."""
    chart = ["## Visualization"]
    chart.extend(_status_overview_chart(criticals, todos, fixmes, docs))
    chart.extend(_module_breakdown_chart(criticals, todos, fixmes))
    return "\n".join(chart)


def _build_summary_lines(
    date_s: str,
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    missing_docs: list[Finding],
) -> list[str]:
    """Build header and executive-summary section lines."""
    return [
        f"# Completist Report: {date_s}\n",
        "## Executive Summary",
        f"- **Critical Gaps**: {len(criticals)}",
        f"- **Feature Gaps (TRACKED_TASK)**: {len(todos)}",
        f"- **Technical Debt**: {len(fixmes)}",
        f"- **Documentation Gaps**: {len(missing_docs)}\n",
    ]


def _critical_table_lines(criticals: list[Finding]) -> list[str]:
    """Return markdown lines for the Critical Incomplete table."""
    lines = [
        "\n## Critical Incomplete (Top 50)",
        "| File | Line | Type | Impact | Coverage | Complexity |",
        "|---|---|---|---|---|---|",
    ]
    for item in criticals[:50]:
        imp, cov, comp = calculate_metrics(item)
        row = (
            f"| `{item['file']}` | {item['line']} | {item['type']}"
            f" | {imp} | {cov} | {comp} |"
        )
        lines.append(row)
    return lines


def _feature_gap_lines(todos: list[Finding]) -> list[str]:
    """Return markdown lines for the Feature Gap Matrix table."""
    lines = [
        "\n## Feature Gap Matrix",
        "| Module | Feature Gap | Type |",
        "|---|---|---|",
    ]
    for item in todos[:50]:
        text = item.get("text", "").replace("|", "\\|")
        lines.append(f"| `{item['file']}` | {text[:100]} | {item['type']} |")
    return lines


def _debt_register_lines(fixmes: list[Finding]) -> list[str]:
    """Return markdown lines for the Technical Debt Register table."""
    lines = [
        "\n## Technical Debt Register",
        "| File | Line | Issue | Type |",
        "|---|---|---|---|",
    ]
    for item in fixmes:
        text = item.get("text", "").replace("|", "\\|")
        lines.append(
            f"| `{item['file']}` | {item['line']} | {text[:100]} | {item['type']} |"
        )
    return lines


def _build_report_lines(
    date_s: str,
    criticals: list[Finding],
    todos: list[Finding],
    fixmes: list[Finding],
    missing_docs: list[Finding],
) -> list[str]:
    """Assemble all markdown report lines from pre-collected findings."""
    report = _build_summary_lines(date_s, criticals, todos, fixmes, missing_docs)
    report.append(generate_mermaid_charts(criticals, todos, fixmes, missing_docs))
    report.extend(_critical_table_lines(criticals))
    report.extend(_feature_gap_lines(todos))
    report.extend(_debt_register_lines(fixmes))
    report.extend(_build_priority_table(criticals, todos))
    return report


def _build_priority_table(criticals: list[Finding], todos: list[Finding]) -> list[str]:
    """Build the Recommended Implementation Order section lines.

    Args:
        criticals: Critical gap findings.
        todos: Feature-gap findings.

    Returns:
        List of markdown lines for the priority table section.
    """

    def priority_score(item: Mapping[str, Any]) -> int:
        """Compute a scalar priority score: high impact minus complexity."""
        imp, _, comp = calculate_metrics(item)
        return (imp * 10) - comp

    all_items = sorted(criticals + todos, key=priority_score, reverse=True)
    lines = [
        "\n## Recommended Implementation Order",
        "Prioritized by Impact (High) and Complexity (Low).",
        "| Priority | File | Issue | Metrics (I/C/C) |",
        "|---|---|---|---|",
    ]
    for i, item in enumerate(all_items[:20], 1):
        imp, cov, comp = calculate_metrics(item)
        desc = item.get("name", item.get("text", ""))[:80].replace("|", "\\|")
        lines.append(f"| {i} | `{item['file']}` | {desc} | {imp}/{cov}/{comp} |")
    return lines


def _save_report_files(date_s: str, report_body: str) -> None:
    """Write the report to a dated file and update COMPLETIST_LATEST.md.

    Args:
        date_s: Date string used in the dated filename (YYYY-MM-DD).
        report_body: Full markdown report content.
    """
    os.makedirs(REPORT_DIR, exist_ok=True)
    report_path = os.path.join(REPORT_DIR, f"Completist_Report_{date_s}.md")
    with open(report_path, "w", encoding="utf-8") as f_out:
        f_out.write(report_body)
    latest_path = os.path.join(REPORT_DIR, "COMPLETIST_LATEST.md")
    with open(latest_path, "w", encoding="utf-8") as f_out:
        f_out.write(report_body)
    logger.info("Report generated: %s", report_path)
