"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import glob
import logging
import os
import re
from collections.abc import Mapping
from typing import Any

from completist_utils import Finding, calculate_metrics

# Constants and Configuration
ISSUES_DIR = "docs/assessments/issues"

logger = logging.getLogger(__name__)


def _issue_file_path(fname_title: str, issue_id: int) -> str:
    """Return the canonical file path for an issue markdown file."""
    return os.path.join(ISSUES_DIR, f"Issue_{issue_id:03d}_{fname_title}.md")


def _issue_header_section(
    title: str, itype: str, f_path: str, l_no: str, labels: list[str]
) -> str:
    """Return front-matter, description, and context sections."""
    front = (
        f'---\ntitle: "{title}"\nlabels: {labels}\n'
        'assignee: "unassigned"\nstatus: "open"\n---\n'
    )
    desc = (
        "\n# Issue Description\n"
        + f"Found critical incomplete implementation in `{f_path}` at line {l_no}.\n\n"
    )
    ctx = f"## Context\n**Type**: {itype} | **Location**: `{f_path}:{l_no}`\n\n"
    return front + desc + ctx


def _issue_body_section(
    context: str, impact: int, coverage: int, complexity: int
) -> str:
    """Return code snippet, metrics, and recommendation sections."""
    code = f"```python\n{context}\n```\n\n"
    metrics = (
        f"## Audit Metrics\n- **Impact**: {impact}/5"
        f" | **Coverage**: {coverage}/5 | **Complexity**: {complexity}/5\n\n"
    )
    rec = (
        "## Recommendation\n"
        "Implement missing logic or document the rationale for the gap.\n"
    )
    return code + metrics + rec


def _build_issue_content(
    title: str,
    itype: str,
    f_path: str,
    l_no: str,
    context: str,
    impact: int,
    coverage: int,
    complexity: int,
    labels: list[str],
) -> str:
    """Return the complete markdown content string for an issue file."""
    return _issue_header_section(
        title, itype, f_path, l_no, labels
    ) + _issue_body_section(context, impact, coverage, complexity)


def create_issue_file(item: Mapping[str, Any], issue_id: int) -> str:
    """Idempotent creation of markdown issue files."""
    os.makedirs(ISSUES_DIR, exist_ok=True)
    itype = str(item.get("type", "Incomplete Implementation"))
    f_path, l_no = str(item["file"]), str(item["line"])
    context = str(item.get("name", item.get("text", "")))
    title = f"Incomplete {itype} in {os.path.basename(f_path)}:{l_no}"
    fname_title = re.sub(r"[^\w]", "_", title).strip("_")
    existing = glob.glob(os.path.join(ISSUES_DIR, f"Issue_*_{fname_title}.md"))
    if existing:
        return existing[0]
    impact, coverage, complexity = calculate_metrics(item)
    labels = ["incomplete-implementation", "critical"]
    if impact >= 5:
        labels.append("high-impact")
    filepath = _issue_file_path(fname_title, issue_id)
    content = _build_issue_content(
        title, itype, f_path, l_no, context, impact, coverage, complexity, labels
    )
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def _create_high_impact_issues(criticals: list[Finding]) -> list[str]:
    """Create issue files for high-impact critical findings and return report lines.

    Args:
        criticals: Sorted list of critical findings.

    Returns:
        List of markdown lines for the "Issues Created" section.
    """
    max_id = 0
    issues_glob = glob.glob(os.path.join(ISSUES_DIR, "Issue_*.md")) + glob.glob(
        os.path.join(ISSUES_DIR, "ISSUE_*.md")
    )
    for issue_p in issues_glob:
        match_id = re.search(r"(\d+)", os.path.basename(issue_p))
        if match_id:
            max_id = max(max_id, int(match_id.group(1)))

    next_id = max_id + 1
    lines = ["\n## Issues Created"]
    for item in [c for c in criticals if calculate_metrics(c)[0] >= 4][:10]:
        lines.append(f"- Created `{create_issue_file(item, next_id)}`")
        next_id += 1
    return lines
