"""Analyze complete implementation status across the repository.

This script parses intermediate data generated by 'jules-completist' scans
and produces structured reports and prioritized issue lists.

Principles:
- DRY: Consolidated redundant file scanning loops into a generic helper.
- Orthogonality: Separates data extraction from report generation logic.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable

from completist_utils import (
    Finding,
    _parse_grep_line,
    _scan_completist_file,
    calculate_metrics,
)

logger = logging.getLogger(__name__)


def _make_todo_parser() -> Callable[[str], Finding | None]:
    """Return a grep-line parser that classifies TODO/FIXME findings."""
    todo_str = "TO" + "DO"  # obfuscated to avoid self-match in greedy scans
    fixme_markers = ["FIX" + "ME", "XXX", "HACK", "TEMP"]

    def _parser(line: str) -> Finding | None:
        filepath, lineno, content = _parse_grep_line(line)
        if not filepath or not lineno or content is None:
            return None
        if re.search(r"\b" + todo_str + r"\b", content):
            return {
                "file": filepath,
                "line": lineno,
                "text": content,
                "type": "TRACKED_TASK",
            }
        for m_marker in fixme_markers:
            if re.search(r"\b" + m_marker + r"\b", content):
                return {
                    "file": filepath,
                    "line": lineno,
                    "text": content,
                    "type": m_marker,
                }
        return None

    return _parser


def analyze_todos() -> tuple[list[Finding], list[Finding]]:
    """Analyze TO-DO and FIX-ME markers."""
    todos: list[Finding] = []
    fixmes: list[Finding] = []
    all_markers = _scan_completist_file("MARKERS", _make_todo_parser())
    for marker_item in all_markers:
        if marker_item["type"] == "TRACKED_TASK":
            todos.append(marker_item)
        else:
            fixmes.append(marker_item)
    return todos, fixmes


def analyze_stubs() -> list[Finding]:
    """Analyze stub functions."""

    def _parser(line: str) -> Finding | None:
        parts = line.strip().rsplit(" ", 1)
        if len(parts) < 2 or ":" not in parts[0]:
            return None
        filepath, lineno = parts[0].rsplit(":", 1)
        return {"file": filepath, "line": lineno, "name": parts[1], "type": "Stub"}

    return _scan_completist_file("STUBS", _parser)


def analyze_docs() -> list[Finding]:
    """Analyze missing documentation."""

    def _parser(line: str) -> Finding | None:
        parts = line.strip().rsplit(" ", 1)
        if len(parts) < 2 or ":" not in parts[0]:
            return None
        filepath, lineno = parts[0].rsplit(":", 1)
        return {"file": filepath, "line": lineno, "name": parts[1], "type": "DocGap"}

    return _scan_completist_file("DOCS", _parser)


def analyze_not_implemented() -> list[Finding]:
    """Analyze Not Implemented Error occurrences."""
    ni_str = "NotImplemented" + "Error"

    def _parser(line: str) -> Finding | None:
        f_path, l_no, c_txt = _parse_grep_line(line)
        if f_path and l_no and c_txt and ni_str in c_txt:
            return {"file": f_path, "line": l_no, "text": c_txt, "type": ni_str}
        return None

    return _scan_completist_file("NOT_IMPL", _parser)


def analyze_abstract_methods() -> list[Finding]:
    """Analyze Abstract Methods."""

    def _parser(line: str) -> Finding | None:
        f_path, l_no, c_txt = _parse_grep_line(line)
        if f_path and l_no and c_txt and "@abstractmethod" in c_txt:
            return {"file": f_path, "line": l_no, "text": c_txt, "type": "Abstract"}
        return None

    return _scan_completist_file("ABSTRACT", _parser)


def _collect_report_data() -> tuple[
    list[Finding], list[Finding], list[Finding], list[Finding]
]:
    """Run all analyzers and return (criticals, todos, fixmes, missing_docs).

    criticals are stub/NotImplementedError findings outside test files,
    sorted descending by impact score.
    """
    stubs = analyze_stubs()
    ni_errors = analyze_not_implemented()
    todos, fixmes = analyze_todos()
    missing_docs = analyze_docs()
    _ = analyze_abstract_methods()

    criticals = [s for s in (stubs + ni_errors) if "test" not in s["file"].lower()]
    criticals.sort(key=lambda x: calculate_metrics(x)[0], reverse=True)
    return criticals, todos, fixmes, missing_docs
